branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2017

platform:
  - x86

configuration:
  - Release

environment:
  VCPKG_ROOT: C:\tools\vcpkg

cache: c:\tools\vcpkg\installed\ -> vcpkg-commit.txt, cmake/x86-windows-static-custom.cmake

install:
  - git submodule init
  - git submodule update
  - powershell .\scripts\prepare.ps1
  - c:\tools\vcpkg\vcpkg.exe export --zip --output=export boost-algorithm libiconv nlohmann-json curl libssh2 boost-property-tree boost-asio openssl spdlog sqlite3 boost-process
  - set /p APP_ID=<app_id.txt

build_script:
  - powershell .\scripts\generate.ps1 %CONFIGURATION%
  - powershell .\scripts\build.ps1 %CONFIGURATION%

artifacts:
  - path: build/Release/Release/%APP_ID%
    type: zip
  - path: c:\tools\vcpkg\export.zip
